- common/package-lock.json
- functions/package.json
- package-lock.json
- package.json
> feat: common

- projects/main/src/app/page/home/home-routing.module.ts
- projects/main/src/app/page/home/home.component.html
- projects/main/src/app/page/home/home.component.spec.ts
- projects/main/src/app/page/home/home.component.ts
- projects/main/src/app/page/home/home.module.ts
> feat: home

- .github/workflows/deploy-prod.yml
- .github/workflows/nodejs-common.yml
- .github/workflows/nodejs-functions.yml
- .github/workflows/nodejs-main.yml
- .github/workflows/nodejs-shared.yml
- functions/package-lock.json
- functions/package.json
- package-lock.json
- package.json
- projects/main/src/app/view/home/home.module.ts
> feat: @local/common

- projects/main/src/app/view/accounts/enter/enter.component.css
- projects/main/src/app/view/accounts/enter/enter.component.html
09/09 Meetingで使用したSign In画面のSign UpリンクをrouterLink化したバージョンです。
その変更のみ。
@KimuraYu45z
確認お願いします。
@Tomosuke0930 
他の箇所でも使っているのでrouterLinkの使い方も軽く目を通しておいていただけると助かります。
> chore: enter component router link

- projects/main/src/app/view/accounts/create/create.component.css
- projects/main/src/app/view/accounts/create/create.component.html
プルリクエスト作成してから画面に間違いに気づきました。
すぐに修正させていただきますので少々お待ちください。
> fix: coding-sign-up

- projects/main/src/app/view/home/home.component.css
- projects/main/src/app/view/home/home.component.html
Homeのデザインを若干変更
将来的にはランニングページにする予定
> chore: デザインを若干マシに

- projects/main/src/index.html
> feat: material component

- projects/main/src/app/view/txs/buy/buy.component.html
#13 
間違えました。すぐに削除します
images.githubusercontent.com/84496536/132805649-7ed2e2f7-19a5-4f56-bca5-d6fa2c7e978b.png">
> fix: coding-buy2

- projects/main/src/app/page/txs/tx/tx.component.ts
- projects/main/src/app/page/txs/txs.component.ts
- projects/main/src/app/view/txs/tx/tx.component.ts
- projects/main/src/app/view/txs/txs.component.ts
Any型のObservableを修正
@KimuraYu45z アドバイスありがとうございました。
> fix: txs tx fix observable any

- projects/main/src/app/view/accounts/create/create.component.html
- projects/main/src/app/view/accounts/enter/enter.component.html
@Senna46 @KimuraYu45z 
現在Textfieldの動作がうまくいかないため臨時でTextFieldsを変更しました。
またコメントアウトができなかったためhiddenを使ってMaterialUiでのTextFieldsは表示しないようにしました。
レビューお願い致します。
> fix: change-text-fields

- docs/Seq02_GenerateToken.plantuml
- projects/main/src/app/view/home/home.component.html
- projects/main/src/app/view/txs/txs.component.html
> chore: fix type miss

- projects/main/src/app/view/accounts/create/create.component.css
- projects/main/src/app/view/accounts/create/create.component.html
- projects/main/src/app/view/accounts/enter/enter.component.css
- projects/main/src/app/view/accounts/enter/enter.component.html
- projects/main/src/app/view/txs/txs.component.css
> fix: button color

- projects/main/src/app/view/accounts/create/create.component.html
- projects/main/src/app/view/accounts/enter/enter.component.html
> chore: sigh up in miss

- docs/Seq_ElectoricPowerExchange.plantuml
全部まとめて不要なものを削除したシーケンス図を作成
Tx部分が若干冗長な気がするので良い案を思いついたら変更予定
> feat: add sequence plantuml

- projects/main/src/app/view/txs/buy/buy.component.html
- projects/main/src/app/view/txs/sell/sell.component.html
> chore: buy and sell

- angular.json
- package-lock.json
- package.json
- projects/main/src/app/app.module.ts
- projects/main/src/app/material.module.ts
- projects/main/src/index.html
- projects/main/src/styles.css
とりあえずAngular-Materialのインストールのみ
変更を加えていって，最終的にMaterial Componentを削除する方針です
@KimuraYu45z 念のため確認お願いします。Cosmoscanを参考にできるのでこちらの方がやりやすいと思いました。
また，レイアウトはFlex-Layoutではなく，Tailwindでやるという方針で違和感ないでしょうか？
> feat: install angular material

- projects/main/src/app/view/txs/txs.component.html
- projects/main/src/app/view/txs/txs.module.ts
txsをAngular Material化
一旦，text sizeとmarginを一旦削除
@Tomosuke0930 
mat-card, mat-list-itemの参考にどうぞ
> feat: angular-material

- projects/main/src/app/view/accounts/create/create.component.css
- projects/main/src/app/view/accounts/create/create.component.html
- projects/main/src/app/view/accounts/create/create.component.ts
- projects/main/src/app/view/accounts/create/create.module.ts
- projects/main/src/app/view/accounts/enter/enter.component.css
- projects/main/src/app/view/accounts/enter/enter.component.html
- projects/main/src/app/view/accounts/enter/enter.module.ts
#13 
@Senna46 @KimuraYu45z 
レビューお願い致します。
Sign Upの画面
Sign Inの画面
> Feature/create change UI&angular material

- functions/.eslintrc.js
- functions/package-lock.json
- functions/package.json
> chore: eslint

- projects/shared/src/lib/services/auth/auth.service.ts
- projects/shared/src/lib/services/auth/auto-id.ts
@KimuraYu45z  以下の関数の追加でアカウント作成時の問題は解決
```
export function autoId() {
const CHARS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789';
let autoId = '';
for (let i = 0; i < 20; i++) {
autoId += CHARS.charAt(Math.floor(Math.random() * CHARS.length));
}
return autoId;
}
```
一方、Sign inのext/user-not-foundの問題は未解決
> feat: autoid

- projects/main/src/app/page/accounts/account/account.component.html
- projects/main/src/app/page/accounts/account/account.component.ts
- projects/main/src/app/view/accounts/account/account.component.html
- projects/main/src/app/view/accounts/account/account.component.ts
- projects/main/src/app/view/accounts/account/account.module.ts
@angular/fire/authのバージョン変更に伴う修正
> Authのぬるぽエラー修正

- .firebaserc
- functions/package-lock.json
- functions/package.json
- projects/main/src/environments/environment.prod.ts
- projects/main/src/environments/environment.ts
なぜかだめだがインフラまっさらにしたのでとりあえずマージ希望
昔のfirebaseプロジェクトはプロジェクトごと削除で良い
> feat: firebase project

- projects/main/src/app/page/txs/buy/buy.component.ts
- projects/main/src/app/page/txs/sell/sell.component.ts
> fix: tx request add uid

- projects/main/src/app/app.component.html
- projects/main/src/app/app.component.ts
- projects/main/src/app/view/app.component.html
- projects/main/src/app/view/app.component.ts
- projects/main/src/app/view/home/home.component.html
ログインするとサインアウトにボタンが変更するapp.componentが何故か死んでいたので再実装
> fix: sign out

- projects/shared/src/lib/services/normal-ask/normal-ask.application.service.ts
- projects/shared/src/lib/services/normal-bids/normal-bid.application.service.ts
- projects/shared/src/lib/services/renewable-ask/renewable-ask.application.service.ts
- projects/shared/src/lib/services/renewable-bid/renewable-bid.application.service.ts
Bid Askを行うときに何も表示されないので、Dialogを開くように変更。
リダイレクトもTransactionのトップページに変更しています。
tx-protoをマージ先にしています。
> application.service.ts  add dialog & redirect

- common/proto/balance_snapshot/balance_snapshot.proto
- common/proto/balances/balance.proto
- common/proto/histories/history.proto
- common/proto/monthly_clearances/monthly_clearance.proto
- common/proto/monthly_usages/monthly_usage.proto
- common/proto/normal-bid-histories/normal-bid-history.proto
- common/proto/normal_ask_histories/normal_ask_history.proto
- common/proto/normal_asks/normal_ask.proto
- common/proto/normal_bids/normal_bid.proto
- common/proto/normal_settlements/normal_settlement.proto
- common/proto/primary_asks/primary_ask.proto
- common/proto/primary_bids/primary_bid.proto
- common/proto/renewable-bid-histories/renewable-bid-history.proto
- common/proto/renewable_ask_histories/renewable_ask_history.proto
- common/proto/renewable_asks/renewable_ask.proto
- common/proto/renewable_bids/renewable_bid.proto
- common/proto/single_price_normal_settlements/single_price_normal_settlement.proto
- common/proto/single_price_renewable_settlements/single_price_renewable_settlement.proto
- common/proto/solar_power/solar_power.proto
- common/proto/transactions/transaction.proto
- common/proto/utility_power/utility_power.proto
- common/src/proto.cjs
- common/src/proto.d.ts
- common/src/proto.js
> feat: uint32=>double

- projects/main/src/app/page/txs/history/solar/ask/ask.component.html
- projects/main/src/app/page/txs/history/solar/ask/ask.component.ts
- projects/main/src/app/page/txs/history/solar/bid/bid.component.html
- projects/main/src/app/page/txs/history/solar/bid/bid.component.ts
- projects/main/src/app/page/txs/history/solar/solar-routing.module.ts
- projects/main/src/app/page/txs/history/solar/solar.module.ts
- projects/main/src/app/page/txs/history/utility/ask/ask.component.html
- projects/main/src/app/page/txs/history/utility/ask/ask.component.ts
- projects/main/src/app/page/txs/history/utility/bid/bid.component.html
- projects/main/src/app/page/txs/history/utility/bid/bid.component.ts
- projects/main/src/app/page/txs/history/utility/utility-routing.module.ts
- projects/main/src/app/page/txs/history/utility/utility.module.ts
- projects/main/src/app/page/txs/order/utility/utility-routing.module.ts
- projects/main/src/app/page/txs/txs-routing.module.ts
- projects/main/src/app/view/txs/history/solar/ask/ask.component.html
- projects/main/src/app/view/txs/history/solar/ask/ask.component.ts
- projects/main/src/app/view/txs/history/solar/ask/ask.module.ts
- projects/main/src/app/view/txs/history/solar/bid/bid.component.html
- projects/main/src/app/view/txs/history/solar/bid/bid.component.ts
- projects/main/src/app/view/txs/history/solar/bid/bid.module.ts
- projects/main/src/app/view/txs/history/utility/ask/ask.component.html
- projects/main/src/app/view/txs/history/utility/ask/ask.component.ts
- projects/main/src/app/view/txs/history/utility/ask/ask.module.ts
- projects/main/src/app/view/txs/history/utility/bid/bid.component.html
- projects/main/src/app/view/txs/history/utility/bid/bid.component.ts
- projects/main/src/app/view/txs/history/utility/bid/bid.module.ts
> feat: history

- projects/main/src/app/page/txs/history/utility/bid/bid.component.html
- projects/main/src/app/page/txs/history/utility/bid/bid.component.ts
- projects/main/src/app/page/txs/txs.component.ts
- projects/main/src/app/view/txs/history/utility/bid/bid.component.html
- projects/main/src/app/view/txs/history/utility/bid/bid.component.ts
- projects/shared/src/lib/services/primary-bids/primary-bid.application.service.ts
- projects/shared/src/lib/services/primary-bids/primary-bid.infrastructure.service.ts
- projects/shared/src/lib/services/primary-bids/primary-bid.service.ts
Tx一覧画面に月初のトークン付与について表示する機能がないのに気づいたので追加
動作はFuctionが動くようになってからなのでとりあえずこれでマージします。
> feat: txsでprimary-bidを確認可能にする変更

- functions/src/balances/daily-usage.ts
日々の残高引き落とし
とりあえず再エネトークン優先で引き落とす設定でFunctionを記載
将来的には優先設定を追加しても良さそう
> feat: daily usage withdraw

- projects/main/src/app/page/txs/buy/buy.component.html
- projects/main/src/app/page/txs/buy/buy.component.ts
- projects/main/src/app/page/txs/history/solar/ask/ask.component.ts
- projects/main/src/app/page/txs/history/solar/bid/bid.component.ts
- projects/main/src/app/page/txs/history/utility/ask/ask.component.ts
- projects/main/src/app/page/txs/history/utility/bid/bid.component.ts
- projects/main/src/app/page/txs/order/solar/ask/ask.component.ts
- projects/main/src/app/page/txs/order/solar/bid/bid.component.ts
- projects/main/src/app/page/txs/order/utility/ask/ask.component.ts
- projects/main/src/app/page/txs/order/utility/bid/bid.component.ts
- projects/main/src/app/page/txs/sell/sell.component.html
- projects/main/src/app/page/txs/sell/sell.component.ts
- projects/main/src/app/page/txs/txs.component.ts
- projects/main/src/app/view/txs/buy/buy.component.ts
- projects/main/src/app/view/txs/sell/sell.component.ts
#145 
Student Account IDが入っていない問題を修正
Dashboardは @KokiKumagai に任せます
> Student account

- common/proto/monthly_payments/monthly_payment.proto
- common/proto/monthly_usages/monthly_usage.proto
- common/src/proto.cjs
- common/src/proto.d.ts
- common/src/proto.js
- functions/src/monthly-payments/calculate-payment.ts
- projects/main/src/app/view/accounts/account/account.component.html
Timestamp型を直接HTMLで表示することはできないので、protoにyearとmonthのフィールドを追加
Timestamp型をts側でtoDate()しても良いが、計算が追加で必要になり面倒なのでfunction側にて年月の計算を実装
> feat: add year month field

- .gitignore
- firestore.rules
- projects/main/src/app/app.module.ts
- projects/main/src/environments/environment.prod.ts
- projects/main/src/environments/environment.ts
Firebase Emullatorを設定してみましたが、Functionが動作しない&アカウント作成でエラーが出ます。
`
FirebaseError: Server responded with status 500
`
FunctionはOnCreateがそもそも発火しません。
とりあえずテストまではFirebaseを使ってデバッグできると思うので、そっちでデバッグします
> Firebase Emulator

- projects/main/src/app/page/accounts/account/account.component.ts
- projects/main/src/app/view/accounts/account/account.component.html
> fix: margin and dummy data

- projects/main/src/app/page/dashboard/dashboard.component.html
- projects/main/src/app/page/dashboard/dashboard.component.ts
- projects/main/src/app/view/dashboard/dashboard.component.html
- projects/main/src/app/view/dashboard/dashboard.component.ts
- projects/shared/src/lib/services/student-accounts/balances/balance.application.service.ts
ランキングを表示しようとすると#0になります
ranking.id == account.id　はtrueですがrankをconsoleすると-1を出力するのでcombineLatestのエラーが起きています
> feat: dashboard-ranking

- functions/src/balances/daily-usage.spec.ts
- functions/src/balances/daily-usage.ts
close #117 
日々の引き落としのFunctionの修正とそのテスト
あとはエネルギーサーバーからのメールを受けて、DailyUsageをFirebase上に作成することができればBalanceからの引き落としも含めて動作する
> Daily usage test

- functions/src/accounts/controller.ts
- functions/src/admin-accounts/controller.ts
- functions/src/available-balances/controller.ts
- functions/src/balance-snapshots/controller.ts
- functions/src/balances/controller.ts
- functions/src/daily-usages/controller.ts
- functions/src/discount-prices/controller.ts
- functions/src/market-statuses/controller.ts
- functions/src/monthly-payments/controller.ts
- functions/src/monthly-usages/controller.ts
- functions/src/normal-ask-histories/controller.ts
- functions/src/normal-asks/controller.ts
- functions/src/normal-bid-histories/controller.ts
- functions/src/normal-bids/controller.ts
- functions/src/normal-settlements/controller.ts
- functions/src/primary-asks/controller.ts
- functions/src/primary-bids/controller.ts
- functions/src/renewable-ask-histories/controller.ts
- functions/src/renewable-asks/controller.ts
- functions/src/renewable-asks/primary.ts
- functions/src/renewable-bid-histories/controller.ts
- functions/src/renewable-bids/controller.ts
- functions/src/renewable-settlements/controller.ts
- functions/src/single-price-normal-settlements/controller.ts
- functions/src/single-price-normal-settlements/normal-contract.ts
- functions/src/single-price-renewable-settlements/controller.ts
- functions/src/single-price-renewable-settlements/renewable-contract.ts
- functions/src/student-accounts/controller.ts
> Function region

- functions/src/single-price-normal-settlements/normal-contract.spec.ts
- functions/src/single-price-normal-settlements/normal-contract.ts
- functions/src/single-price-renewable-settlements/renewable-contract.ts
昨日のFunctionでエラー出てたので修正
Bid, Askが存在しないときに走らなくていいものも動いていた
> fix: returnの位置のミス

- package.json
#172 のようなトラブルを未然に防ぐため
Close #173
> feat: preinstallにfunctionsを追加

- functions/src/balances/module.ts
- functions/src/daily-usages/controller.ts
- functions/src/normal-ask-deletes/controller.ts
- functions/src/normal-bid-deletes/controller.ts
- functions/src/renewable-ask-deletes/controller.ts
- projects/main/src/app/page/accounts/account/account.component.html
- projects/main/src/app/page/accounts/account/account.component.ts
- projects/main/src/app/view/accounts/account/account.component.html
- projects/main/src/app/view/accounts/account/account.component.ts
Daily Usageでの引き落としに問題があったので対処
#171 これにてDailyUsageでのBalance引き落としは完全に動作を確認
> Fix dailyusage

- common/proto/account-private/account-private.proto
- common/proto/student_accounts/student_account.proto
- common/src/entities/student-accounts/account-privates/account-private.firestore.ts
- common/src/entities/student-accounts/account-privates/account-private.ts
- common/src/entities/student-accounts/account-privates/index.ts
- common/src/index.ts
- common/src/proto.cjs
- common/src/proto.d.ts
- common/src/proto.js
- functions/package-lock.json
- functions/package.json
- functions/src/account-privates/controller.ts
- functions/src/account-privates/index.ts
- functions/src/account-privates/module.ts
- functions/src/renewable-asks/primary.ts
- functions/src/single-price-normal-settlements/normal-contract.spec.ts
- functions/src/single-price-normal-settlements/normal-contract.ts
- functions/src/single-price-renewable-settlements/renewable-contract.ts
- functions/src/student-accounts/xrpl.spec.ts
- functions/src/student-accounts/xrpl.ts
- package-lock.json
- package.json
RenewableAskのPrimaryの生成時間を朝9時に変更
下記のようにBidのindexが行き過ぎてエラーが出る問題に対処
```
TypeError: Cannot read property 'price' of undefined
at /workspace/lib/single-price-normal-settlements/normal-contract.js:72:58
```
XRP Ledger関連のコードもウォレット作成部分のみこれに含めて合わせてマージ予定 #180
> Function fix0127

- common/proto/admin-private/admin-private.proto
- common/proto/daily_usages/daily_usage.proto
- common/src/entities/admin-accounts/admin-privates/admin-private.firestore.ts
- common/src/entities/admin-accounts/admin-privates/admin-private.ts
- common/src/entities/admin-accounts/admin-privates/index.ts
- common/src/index.ts
- common/src/proto.cjs
- common/src/proto.d.ts
- common/src/proto.js
- functions/src/admin-accounts/module.ts
- functions/src/admin-privates/controller.ts
- functions/src/admin-privates/index.ts
- functions/src/admin-privates/module.ts
- functions/src/balances/daily-usage.ts
- functions/src/balances/normal-settlement.ts
- functions/src/balances/renewable-settlemet.ts
- functions/src/balances/student-account.ts
- functions/src/index.ts
- functions/src/primary-asks/balance-snapshot.spec.ts
- functions/src/primary-asks/balance-snapshot.ts
- functions/src/student-accounts/xrpl.spec.ts
- functions/src/student-accounts/xrpl.ts
- projects/main/src/app/view/accounts/account/account.component.html
> XRPL test netへの接続

- functions/src/balances/normal-settlement.ts
- functions/src/balances/renewable-settlemet.ts
- functions/src/single-price-normal-settlements/normal-contract.spec.ts
- functions/src/single-price-normal-settlements/normal-contract.ts
- functions/src/single-price-renewable-settlements/renewable-contract.ts
例外処理が間違っており、成約するはずのBid, Askが１つずつの場合制約なしで終了してしまう問題への対処
> Fix auction

- common/src/entities/student-accounts/balance-snapshots/balance-snapshot.firestore.ts
- common/src/index.ts
- functions/src/balance-snapshots/market-status.ts
- functions/src/balance-snapshots/module.ts
- functions/src/monthly-payments/balance-snapshot.ts
- functions/src/primary-asks/monthly-usage.ts
- functions/src/single-price-normal-settlements/normal-contract.ts
- functions/src/single-price-renewable-settlements/renewable-contract.ts
マージしないこと
定期実行を変更
- 10分おきにオークションが実行される
- x月1日でなくても月初のFunctionが動く
> 月次Functionの動作

- angular.json
- projects/main/src/app/page/dashboard/dashboard.component.html
- projects/main/src/app/page/dashboard/dashboard.component.ts
- projects/main/src/app/view/dashboard/dashboard.component.html
- projects/main/src/app/view/dashboard/dashboard.component.ts
- projects/shared/src/lib/services/student-accounts/monthly-usages/monthly-usage.application.service.ts
- projects/shared/src/lib/services/student-accounts/monthly-usages/monthly-usage.infrastructure.service.ts
- projects/shared/src/lib/services/student-accounts/monthly-usages/monthly-usage.service.ts
close #185 
Balanceの円グラフは完璧に動作
あれ、これ日時ではと思ったらDailyUsageをなぜか使っていたので修正する
明日か来週に対応予定
> Dashboard observable

- projects/main/src/app/view/accounts/accounts.component.html
- projects/main/src/app/view/accounts/accounts.module.ts
- projects/main/src/app/view/admin/admin.component.html
- projects/main/src/app/view/admin/admin.module.ts
/accounts, /admin のルートのページを作り忘れていたので作成
CI通ればマージします
> function menu

- projects/main/src/app/page/accounts/account/account.component.ts
- projects/shared/src/lib/services/auth/auth.application.service.ts
close #203 
@Ryo0731 本件レビューお願いします。Files changedタブのレビューからApproveを選択。コメントなしでも「LGTM」のようなコメントでも良いのでFileの変更を見てApproveしてください。
`this.location.back();`だと、login後、Sign upのページに飛ぶのでアカウント詳細ページに飛ぶように設定。
また、この条件だと、StudentAccount$の中身がundefinedになり、undefinedの参照エラーが出るので、その場合nullを返すように変更して対応。
> ログインのRouting

- projects/main/src/app/page/admin/admin.component.ts
- projects/main/src/app/page/admin/xrpl/xrpl.component.html
- projects/main/src/app/page/admin/xrpl/xrpl.component.ts
- projects/main/src/app/view/admin/admin.module.ts
- projects/main/src/app/view/admin/xrpl/xrpl.component.html
- projects/main/src/app/view/admin/xrpl/xrpl.component.ts
- projects/main/src/app/view/admin/xrpl/xrpl.module.ts
> admin/xrpl のページ実装

- functions/src/balance-snapshots/market-status.ts
- functions/src/normal-ask-settings/module.ts
- functions/src/normal-asks/primaryAdditional.ts
- functions/src/renewable-ask-settings/module.ts
- functions/src/renewable-asks/primary.ts
#210 に纏わるFunctionの整備
該当Issue #202
> トークン追加発行の仕様変更

- projects/main/src/app/page/dashboard/dashboard.component.html
- projects/main/src/app/page/dashboard/dashboard.component.ts
- projects/main/src/app/view/dashboard/dashboard.component.html
- projects/main/src/app/view/dashboard/dashboard.component.ts
システムが毎日行う介入をフロントから見ることができるように変更。
> マーケットの介入状況をフロントに表示

- projects/main/src/app/view/accounts/create/create.component.ts
close #274
部屋を指定せずにアカウントを作成できてしまう問題を修正。
> 部屋指定なしでアカウントを作成できる不具合の修正

- projects/main/src/app/page/accounts/account/account.component.html
- projects/main/src/app/page/accounts/account/account.component.ts
- projects/main/src/app/page/dashboard/charts/charts.component.ts
- projects/main/src/app/page/dashboard/dashboard.component.html
- projects/main/src/app/page/dashboard/dashboard.component.ts
- projects/main/src/app/view/accounts/account/account.component.html
- projects/main/src/app/view/accounts/account/account.component.ts
- projects/main/src/app/view/accounts/account/account.module.ts
- projects/main/src/app/view/dashboard/dashboard.component.html
- projects/main/src/app/view/dashboard/dashboard.component.ts
- projects/shared/src/lib/services/student-accounts/daily-payments/daily-payment.application.service.ts
- projects/shared/src/lib/services/student-accounts/daily-payments/daily-payment.infrastructure.service.ts
- projects/shared/src/lib/services/student-accounts/daily-payments/daily-payment.service.ts
> CO2 ranking

- functions/src/daily-payments/create-balance.ts
- functions/src/daily-payments/module.ts
- functions/src/index.ts
- functions/src/schedules/contract-normal.ts
- functions/src/schedules/contract-renewable.ts
- functions/src/schedules/daily-withdraw.ts
- functions/src/schedules/monthly-settlement.ts
- functions/src/schedules/operation-normal.ts
- functions/src/schedules/operation-renewable.ts
定期実行を短時間に変更し、バックエンドの動作を確認する
#218
> バックエンドの動作確認及び修正

- functions/src/daily-payments/create-balance.ts
- functions/src/index.ts
- functions/src/schedules/contract-normal.ts
- functions/src/schedules/contract-renewable.ts
- functions/src/schedules/daily-withdraw.ts
- functions/src/single-price-normal-settlements/create-normal-settlement.ts
- functions/src/single-price-renewable-settlements/create-renewable-settlement.ts
- projects/shared/src/lib/services/student-accounts/balances/balance.application.service.ts
> [TEST] feat: ゼロ成約の表示追加 

- functions/src/daily-payments/create-balance.ts
- functions/src/normal-settlements/create-balance.ts
- functions/src/renewable-settlements/create-balance.ts
- functions/src/schedules/daily-withdraw.ts
- functions/src/single-price-normal-settlements/create-normal-settlement.ts
- functions/src/single-price-renewable-settlements/create-renewable-settlement.ts
> [TEST] XRPL処理を直列化する

- common/proto/account_private/account_private.proto
- common/src/proto.cjs
- common/src/proto.d.ts
- common/src/proto.js
- functions/package-lock.json
- functions/package.json
- functions/src/account-privates/module.ts
- functions/src/index.ts
- functions/src/schedules/send-mails.ts
- functions/src/student-accounts/xrpl.ts
- projects/main/src/app/page/accounts/create/create.component.ts
- projects/shared/src/lib/services/room-changes/room-change.application.service.ts
- projects/shared/src/lib/services/student-accounts/account-privates/account-private.application.service.ts
- projects/shared/src/lib/services/student-accounts/account-privates/account-private.infrastructure.service.ts
- projects/shared/src/lib/services/student-accounts/account-privates/account-private.service.ts
> [TEST] 注文していないユーザーへのリマインドメール

- common/proto/account_private/account_private.proto
- common/src/proto.cjs
- common/src/proto.d.ts
- common/src/proto.js
- functions/package-lock.json
- functions/package.json
- functions/src/account-privates/module.ts
- functions/src/index.ts
- functions/src/schedules/send-mails.ts
- functions/src/student-accounts/xrpl.ts
- projects/main/src/app/page/accounts/create/create.component.ts
- projects/shared/src/lib/services/room-changes/room-change.application.service.ts
- projects/shared/src/lib/services/student-accounts/account-privates/account-private.application.service.ts
- projects/shared/src/lib/services/student-accounts/account-privates/account-private.infrastructure.service.ts
- projects/shared/src/lib/services/student-accounts/account-privates/account-private.service.ts
> 注文していないユーザーへのリマインドメール

- functions/src/daily-payments/controller.ts
- functions/src/normal-settlements/controller.ts
- functions/src/renewable-settlements/controller.ts
使用していないFunctionを削除
以下のようなスケーラビリティのエラーが出るのを防ぐ
```
normal_settlements-normal_settlement-onCreate
The request was aborted because there was no available instance. Additional troubleshooting documentation can be found at: https://cloud.google.com/functions/docs/troubleshooting#scalability
```
> chore: delete unused function

- projects/main/src/app/page/accounts/account/account.component.ts
- projects/main/src/app/page/accounts/xrpl/xrpl.component.ts
- projects/main/src/app/page/admin/dashboard/dashboard.component.html
- projects/main/src/app/page/admin/dashboard/dashboard.component.ts
- projects/main/src/app/page/dashboard/dashboard.component.ts
- projects/main/src/app/view/admin/dashboard/dashboard.component.html
- projects/main/src/app/view/admin/dashboard/dashboard.component.ts
- projects/shared/src/lib/services/csvs/csv-common.service.ts
- projects/shared/src/lib/services/csvs/csv-daily-usages/csv-daily-usages.service.ts
- projects/shared/src/lib/services/csvs/csv-downloads/csv-download.service.ts
- projects/shared/src/lib/services/csvs/csv-order-histories/csv-order-histories.service.ts
- projects/shared/src/lib/services/normal-ask-histories/normal-ask-history.application.service.ts
- projects/shared/src/lib/services/normal-bid-histories/normal-bid-history.application.service.ts
- projects/shared/src/lib/services/renewable-ask-histories/renewable-ask-history.application.service.ts
- projects/shared/src/lib/services/renewable-bid-histories/renewable-bid-history.application.service.ts
- projects/shared/src/lib/services/student-accounts/balances/balance.application.service.ts
管理者Dashboardに以下の機能を追加
- DailyUsage（すべての部屋）のダウンロード
- DailyPayment（ユーザーが何でDailyUsageを支払ったか）のダウンロード
To Do
- Admin Dashboardのservice切り出しでの読み込み高速化
> CSVダウンロード機能の拡充

- projects/main/src/app/page/accounts/account/account.component.html
- projects/main/src/app/page/accounts/account/account.component.ts
- projects/main/src/app/page/admin/dashboard/dashboard.component.html
- projects/main/src/app/page/admin/dashboard/dashboard.component.ts
- projects/main/src/app/page/dashboard/charts/charts.component.ts
- projects/main/src/app/page/dashboard/dashboard.component.html
- projects/main/src/app/page/dashboard/dashboard.component.ts
- projects/main/src/app/page/txs/buy/buy.component.ts
- projects/main/src/app/page/txs/sell/sell.component.ts
- projects/main/src/app/view/accounts/account/account.component.ts
- projects/main/src/app/view/admin/dashboard/dashboard.component.ts
- projects/main/src/app/view/dashboard/charts/charts.component.ts
- projects/main/src/app/view/dashboard/dashboard.component.css
- projects/main/src/app/view/dashboard/dashboard.component.html
- projects/main/src/app/view/dashboard/dashboard.component.ts
- projects/shared/src/lib/services/charts/chart-balances/chart-balance.service.ts
- projects/shared/src/lib/services/charts/chart-contracts/chart-contract.service.ts
- projects/shared/src/lib/services/charts/chart-monthly-usages/chart-monthly-usage.service.ts
- projects/shared/src/lib/services/charts/chart-orders/chart-order.service.ts
- projects/shared/src/lib/services/csvs/csv-downloads/csv-download.service.ts
- projects/shared/src/lib/services/single-price-normal-settlements/single-price-normal-settlement.application.service.ts
- projects/shared/src/lib/services/single-price-renewable-settlements/single-price-renewable-settlement.application.service.ts
dashboardの読み込み高速化に関するPR
- ダウンロードされるCSV内の1000000倍表示を廃止
- 冗長なコードの整理
- Dashboardの読み込み高速化
> Dashboard関連のリファクタリング

- functions/src/schedules/contract-normal.ts
- functions/src/schedules/contract-renewable.ts
- functions/src/single-price-normal-settlements/controller.ts
- functions/src/single-price-normal-settlements/create-normal-settlement.ts
- functions/src/single-price-renewable-settlements/controller.ts
- functions/src/single-price-renewable-settlements/create-renewable-settlement.ts
single_price_normal_settlement-onCreateにおいて下記の問題が再発していたのでそれを解決するためのPR
```
The request was aborted because there was no available instance. Additional troubleshooting documentation can be found at: https://cloud.google.com/functions/docs/troubleshooting#scalability 
```
動作未確認です
> single_price_normal_settlement-onCreateの修正

- functions/src/daily-payments/create-balance.ts
- functions/src/monthly-usages/create-primary-ask.ts
- functions/src/normal-settlements/create-balance.ts
- functions/src/primary-asks/create-balance.ts
- functions/src/renewable-settlements/create-balance.ts
- functions/src/student-accounts/xrpl.ts
今日初めてシステムからの買い注文が発生し、以下エラーが発生。
```
TypeError: Cannot read property 'amount_uupx' of undefined
at normalSettlementOnCreate (/workspace/lib/normal-settlements/create-balance.js:20:49)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async singlePriceNormalSettlementOnCreate (/workspace/lib/single-price-normal-settlements/create-normal-settlement.js:125:13)
at async /workspace/lib/schedules/contract-normal.js:155:9 
```
システムからの買い注文でもエラーが起きないように修正
また、XRPLがエラーの場合の挙動を一部修正（主にテストネット用）
> オークション後の残高処理エラーの修正

- functions/src/schedules/daily-withdraw.ts
電気使用量が０だった場合にもDailyPaymentを作成するように変更
> DailyPaymentの修正

- functions/src/cost-settings/calc-monthly-payment.ts
月末の精算時に計算される割引価格について，割引率をそのまま価格としていた問題を修正。
なお，DiscountPriceのOnCreateは各Documentのアップデートを行うため，今回の問題に伴うFirestoreの修正は不要です。
> 精算時の割引価格の修正

- common/proto/primary_ask_settings/primary_ask_setting.proto
- common/src/entities/primary-ask-settings/index.ts
- common/src/entities/primary-ask-settings/primary-ask-setting.firestore.ts
- common/src/entities/primary-ask-settings/primary-ask-setting.ts
- common/src/index.ts
- common/src/proto.cjs
- common/src/proto.d.ts
- common/src/proto.js
- functions/src/index.ts
- functions/src/monthly-usages/create-primary-ask.ts
- functions/src/primary-ask-settings/controller.ts
- functions/src/primary-ask-settings/index.ts
- functions/src/primary-ask-settings/module.ts
- functions/src/student-accounts/xrpl.ts
- projects/main/src/app/page/admin/tokens/tokens.component.html
- projects/main/src/app/page/admin/tokens/tokens.component.ts
- projects/main/src/app/view/admin/tokens/tokens.component.html
- projects/main/src/app/view/admin/tokens/tokens.component.ts
- projects/shared/src/lib/services/primary-ask-settings/primary-ask-setting.application.service.ts
- projects/shared/src/lib/services/primary-ask-settings/primary-ask-setting.infrastructure.service.ts
- projects/shared/src/lib/services/primary-ask-settings/primary-ask-setting.service.ts
#321 にPrimaryAskの金額と発行量の割合を変更できるAdmin用ページを追加
> PrimaryAskの設定変更機能

- functions/src/index.ts
- functions/src/renewable-ask-settings/update-price.ts
- functions/src/schedules/calc-electricity-cost.ts
電気料金（推測値）を導出するための機能追加PR
あと，Javascript上で最小化問題を求解する必要がある。
> feat: calc electricity cost

- functions/src/schedules/daily-withdraw.ts
- projects/main/src/app/view/dashboard/dashboard.component.html
- DailyPaymentが0で残高更新がなかった際にAvailableBalanceが更新されないことがある問題を修正
- 一部の計算結果でSPX Percentageの表示が0%になることがある問題を修正
> 一部例外での表示の修正

- functions/src/balance-snapshots/calc-monthly-payment.spec.ts
- functions/src/balance-snapshots/calc-monthly-usage.spec.ts
- functions/src/balances/update-available-balance.spec.ts
- functions/src/cost-settings/calc-monthly-payment.spec.ts
- functions/src/daily-payments/create-balance.spec.ts
- functions/src/models/common.model.ts
- functions/src/models/normal-asks/list-valid.data.ts
- functions/src/models/normal-bids/list-valid.data.ts
- functions/src/monthly-usages/create-primary-ask.spec.ts
- functions/src/normal-asks/update-available-balance.spec.ts
- functions/src/normal-settlements/create-balance.spec.ts
- functions/src/primary-asks/create-balance.spec.ts
- functions/src/schedules/calc-electricity-cost.spec.ts
- functions/src/schedules/contract-normal.spec.ts
- functions/src/schedules/daily-withdraw.spec.ts
- functions/src/schedules/monthly-settlement.spec.ts
- functions/src/schedules/monthly-settlement.ts
- functions/src/schedules/operation-normal.spec.ts
- functions/src/schedules/operation-renewable.spec.ts
- functions/src/single-price-normal-settlements/create-normal-settlement.spec.ts
#329 のCIエラーが治らないのでこれで対応します
close https://github.com/KyotoUniv-SIC/electoric-power-exchange/issues/284
https://github.com/KyotoUniv-SIC/electoric-power-exchange/pull/320 の刈り取り
時短のため、データは乱数で生成し、複数回の試行でパターンをテストできるようにする
テストコードは可能な限り、Functionのコードを流用する
今週末を目処に完了予定。
> Firebase Functionのテストコード アップデート

- functions/src/schedules/contract-normal.ts
- functions/src/schedules/contract-renewable.ts
- functions/src/single-price-normal-settlements/create-normal-settlement.ts
- functions/src/single-price-renewable-settlements/create-renewable-settlement.ts
delete_()の使用を廃止し，update()でis_deletedの値を変更する仕様に
動作確認後マージ予定
> 注文の削除について内部処理を変更

- functions/src/cost-settings/calc-monthly-payment.spec.ts
- functions/src/cost-settings/calc-monthly-payment.ts
- functions/src/monthly-usages/create-primary-ask.ts
- functions/src/schedules/operation-normal.spec.ts
- functions/src/schedules/operation-normal.ts
- functions/src/schedules/operation-renewable.spec.ts
- functions/src/schedules/operation-renewable.ts
- functions/src/student-accounts/xrpl.ts
- projects/main/src/app/page/txs/buy/buy.component.ts
- projects/main/src/app/page/txs/sell/sell.component.ts
- projects/main/src/app/view/admin/tokens/tokens.component.html
- projects/main/src/app/view/dashboard/dashboard.component.html
- projects/main/src/app/view/dashboard/reference/reference.component.html
- projects/main/src/app/view/txs/buy/buy.component.html
- projects/main/src/app/view/txs/buy/buy.component.ts
- projects/main/src/app/view/txs/sell/sell.component.html
- projects/main/src/app/view/txs/sell/sell.component.ts
- projects/shared/src/lib/services/charts/chart-contracts/chart-contract.service.ts
- projects/shared/src/lib/services/csvs/csv-downloads/csv-download.service.ts
フロントエンドのトークン価格の変更
SPX価格をUPXとの価格差で決定されるようにする
To Do 01/31
> Price change 2023feb
